// <auto-generated />
using System;
using Menlyn_Mews_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Menlyn_Mews_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Audit_Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Log_Date_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Log_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Audit_Logs");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Booking_Package", b =>
                {
                    b.Property<int>("BookingPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingPackageId"), 1L, 1);

                    b.Property<string>("Booking_Package_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Booking_Package_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Booking_Package_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookingPackageId");

                    b.ToTable("Booking_Packages");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Booking_Review", b =>
                {
                    b.Property<int>("BookingReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingReviewId"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Review_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Review_Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review_Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingReviewId");

                    b.HasIndex("ClientId");

                    b.ToTable("Booking_Reviews");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<string>("Client_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client_Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client_Email_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client_Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client_ID_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client_Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Complaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintId"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Complaint_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Complaint_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaint_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("ComplaintId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ComplaintTypeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Complaint_Type", b =>
                {
                    b.Property<int>("ComplaintTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintTypeId"), 1L, 1);

                    b.Property<string>("Complaint_Type_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComplaintTypeId");

                    b.ToTable("Complaint_Types");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"), 1L, 1);

                    b.Property<string>("Discount_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discount_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount_Percenatage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("DiscountId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Employee_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Contact_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Email_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_ID_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employee_Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Employee_Shift", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Clock_In_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Clock_Out_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Shift_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId", "ShiftId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Employee_Shifts");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Employee_Type", b =>
                {
                    b.Property<int>("EmployeeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeTypeId"), 1L, 1);

                    b.Property<string>("Type_Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeTypeId");

                    b.ToTable("Employee_Types");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Event_Booking", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"), 1L, 1);

                    b.Property<string>("Allergy_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("End_Time")
                        .HasColumnType("time");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Event_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Event_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Event_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Start_Time")
                        .HasColumnType("time");

                    b.HasKey("EventId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("EmployeeId", "ShiftId");

                    b.ToTable("Event_Bookings");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Event_Review", b =>
                {
                    b.Property<int>("EventReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventReviewId"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Event_Review_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Event_Review_Rating")
                        .HasColumnType("int");

                    b.Property<string>("Event_Review_Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventReviewId");

                    b.HasIndex("ClientId");

                    b.ToTable("Event_Reviews");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Event_Types", b =>
                {
                    b.Property<int>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeId"), 1L, 1);

                    b.Property<string>("Event_Capacity_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Event_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventTypeId");

                    b.ToTable("Event_Types");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Inspection_Item", b =>
                {
                    b.Property<int>("InspectionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionItemId"), 1L, 1);

                    b.Property<string>("Inspection_Item_Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inspection_Item_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.HasKey("InspectionItemId");

                    b.HasIndex("InventoryId");

                    b.ToTable("Inspection_Items");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"), 1L, 1);

                    b.Property<int>("InventoryCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Inventory_Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inventory_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inventory_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Maximum_Stock")
                        .HasColumnType("int");

                    b.Property<int?>("Minimum_Stock")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("InventoryCategoryId");

                    b.HasIndex("InventoryTypeId");

                    b.HasIndex("RoomId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Inventory_Category", b =>
                {
                    b.Property<int>("InventoryCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryCategoryId"), 1L, 1);

                    b.Property<string>("Inventory_Category_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inventory_Category_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryCategoryId");

                    b.ToTable("Inventory_Categories");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Inventory_Type", b =>
                {
                    b.Property<int>("InventoryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryTypeId"), 1L, 1);

                    b.Property<string>("Inventory_Type_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inventory_Type_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryTypeId");

                    b.ToTable("Inventory_Types");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Order_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("EmployeeId", "ShiftId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Payment_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Payment_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payment_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Payment_Type", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTypeId"), 1L, 1);

                    b.Property<string>("Payment_Type_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentTypeId");

                    b.ToTable("Payment_Types");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"), 1L, 1);

                    b.Property<string>("Position_Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceId"), 1L, 1);

                    b.Property<DateTime>("Price_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Product_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PriceId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity_On_Hand")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("PriceId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Product_Category", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"), 1L, 1);

                    b.Property<string>("Product_Category_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("Product_Categories");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Product_Type", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductTypeId"), 1L, 1);

                    b.Property<string>("Product_Type_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Type_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductTypeId");

                    b.ToTable("Product_Types");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Receive_Order", b =>
                {
                    b.Property<int>("ReceieveOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceieveOrderId"), 1L, 1);

                    b.Property<string>("Received_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Received_Order_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Received_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReceieveOrderId");

                    b.ToTable("Receive_Orders");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Referrals", b =>
                {
                    b.Property<int>("ReffaralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReffaralId"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount_Percenatge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Expiration_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Redemption_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Redemption_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ref_Discount_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Refferal_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ReffaralId");

                    b.HasIndex("ClientId");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"), 1L, 1);

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Room_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Room_Floor")
                        .HasColumnType("int");

                    b.Property<int?>("Room_Number")
                        .HasColumnType("int");

                    b.Property<decimal>("Room_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Room_Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Room_Booking", b =>
                {
                    b.Property<int>("RoomBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomBookingId"), 1L, 1);

                    b.Property<int?>("BookingPackageId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Booking_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Booking_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Check_In_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Check_Out_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("RoomBookingId");

                    b.HasIndex("BookingPackageId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("RoomId");

                    b.ToTable("Room_Bookings");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Room_Type", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"), 1L, 1);

                    b.Property<string>("Room_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Room_Type_Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Room_Type_Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomTypeId");

                    b.ToTable("Room_Types");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"), 1L, 1);

                    b.Property<DateTime?>("End_TIme")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Shift_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Start_TIme")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Stock_Take", b =>
                {
                    b.Property<int>("StockTakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockTakeId"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Stock_Take_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Total_Items")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StockTakeId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("EmployeeId", "ShiftId");

                    b.ToTable("Stock_Takes");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postal_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Supplier_Address_Line_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Address_Line_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Contact_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Rep_Contact_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Rep_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Rep_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier_Rep_Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.HasIndex("SupplierTypeId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Supplier_Order_Product", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Order_Product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiveOrderId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiveOrderId");

                    b.ToTable("Supplier_Order_Products");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Supplier_Type", b =>
                {
                    b.Property<int>("SupplierTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierTypeId"), 1L, 1);

                    b.Property<string>("Supplier_Type_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierTypeId");

                    b.ToTable("Supplier_Types");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.VAT", b =>
                {
                    b.Property<int>("VATId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VATId"), 1L, 1);

                    b.Property<DateTime>("Creation_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Last_Updated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("VAT_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VATId");

                    b.ToTable("VAT");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Write_Off", b =>
                {
                    b.Property<int>("WriteOffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WriteOffId"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Write_Off_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Write_Off_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Write_Off_Stock_Type_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Write_Off_Stock_Type_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WriteOffId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("EmployeeId", "ShiftId");

                    b.ToTable("Write_Offs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fdd21bd9-9281-46ac-b39f-dceb0c018262",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "f0ea9aa7-1858-4d29-9ef6-2d059a813eaa",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "User"
                        },
                        new
                        {
                            Id = "afb19288-2248-4f9e-95ff-c2a723d42f1a",
                            ConcurrencyStamp = "3",
                            Name = "Manager",
                            NormalizedName = "Manager"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Audit_Log", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Employee", "Employee")
                        .WithMany("Audit_Log")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Booking_Review", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Client", "Client")
                        .WithMany("Booking_Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Complaint", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Client", "Client")
                        .WithMany("Complaint")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Complaint_Type", "Complaint_Type")
                        .WithMany("Complaint")
                        .HasForeignKey("ComplaintTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Employee", "Employee")
                        .WithMany("Complaint")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");

                    b.Navigation("Complaint_Type");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Employee", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Employee_Type", "Employee_Type")
                        .WithMany("Employee")
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Position", "Position")
                        .WithMany("Employee")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee_Type");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Employee_Shift", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Employee", "Employee")
                        .WithMany("Employee_Shift")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Shift", "Shift")
                        .WithMany("Employee_Shift")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Event_Booking", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Client", "Client")
                        .WithMany("Event_Booking")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Event_Types", "Event_Types")
                        .WithMany("Event_Booking")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Employee_Shift", "Employee_Shift")
                        .WithMany("Event_Booking")
                        .HasForeignKey("EmployeeId", "ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee_Shift");

                    b.Navigation("Event_Types");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Event_Review", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Client", "Client")
                        .WithMany("Event_Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Inspection_Item", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Inventory", "Inventory")
                        .WithMany("Inspection_Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Inventory", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Inventory_Category", "InventoryCategory")
                        .WithMany("Inventories")
                        .HasForeignKey("InventoryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Inventory_Type", "InventoryType")
                        .WithMany("Inventories")
                        .HasForeignKey("InventoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Room", "Room")
                        .WithMany("Inventories")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryCategory");

                    b.Navigation("InventoryType");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Order", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Supplier", "Suppliers")
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Employee_Shift", "Employee_Shift")
                        .WithMany("Order")
                        .HasForeignKey("EmployeeId", "ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee_Shift");

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Payment", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Payment_Type", "Payment_Type")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Payment_Type");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Product", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Inventory", "Inventory")
                        .WithMany("Products")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Price", "Price")
                        .WithMany("Product")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Product_Category", "ProductCategory")
                        .WithMany("Product")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Product_Type", "ProductType")
                        .WithMany("Product")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Price");

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Referrals", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Client", "Client")
                        .WithMany("Referrals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Room", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Room_Type", "Room_Type")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room_Type");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Room_Booking", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Booking_Package", "Booking_Package")
                        .WithMany("Room_Booking")
                        .HasForeignKey("BookingPackageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Client", "Clients")
                        .WithMany("Room_Bookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Discount", "Discount")
                        .WithMany("Room_Booking")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Room", "Rooms")
                        .WithMany("Room_Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking_Package");

                    b.Navigation("Clients");

                    b.Navigation("Discount");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Stock_Take", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Inventory", "Inventory")
                        .WithMany("Stock_Take")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Employee_Shift", "Employee_Shift")
                        .WithMany("Stock_Take")
                        .HasForeignKey("EmployeeId", "ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee_Shift");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Supplier", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Supplier_Type", "Supplier_Type")
                        .WithMany("Suppliers")
                        .HasForeignKey("SupplierTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier_Type");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Supplier_Order_Product", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Order", "Order")
                        .WithMany("Supplier_Order_Product")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Product", "Product")
                        .WithMany("Supplier_Order_Product")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Receive_Order", "Receive_Order")
                        .WithMany("Supplier_Order_Product")
                        .HasForeignKey("ReceiveOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Receive_Order");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Write_Off", b =>
                {
                    b.HasOne("Menlyn_Mews_API.Models.Domain.Inventory", "Inventory")
                        .WithMany("Write_Offs")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Menlyn_Mews_API.Models.Domain.Employee_Shift", "Employee_Shift")
                        .WithMany("Write_Off")
                        .HasForeignKey("EmployeeId", "ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee_Shift");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Booking_Package", b =>
                {
                    b.Navigation("Room_Booking");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Client", b =>
                {
                    b.Navigation("Booking_Reviews");

                    b.Navigation("Complaint");

                    b.Navigation("Event_Booking");

                    b.Navigation("Event_Reviews");

                    b.Navigation("Payments");

                    b.Navigation("Referrals");

                    b.Navigation("Room_Bookings");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Complaint_Type", b =>
                {
                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Discount", b =>
                {
                    b.Navigation("Room_Booking");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Employee", b =>
                {
                    b.Navigation("Audit_Log");

                    b.Navigation("Complaint");

                    b.Navigation("Employee_Shift");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Employee_Shift", b =>
                {
                    b.Navigation("Event_Booking");

                    b.Navigation("Order");

                    b.Navigation("Stock_Take");

                    b.Navigation("Write_Off");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Employee_Type", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Event_Types", b =>
                {
                    b.Navigation("Event_Booking");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Inventory", b =>
                {
                    b.Navigation("Inspection_Items");

                    b.Navigation("Products");

                    b.Navigation("Stock_Take");

                    b.Navigation("Write_Offs");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Inventory_Category", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Inventory_Type", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Order", b =>
                {
                    b.Navigation("Supplier_Order_Product");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Payment_Type", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Position", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Price", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Product", b =>
                {
                    b.Navigation("Supplier_Order_Product");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Product_Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Product_Type", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Receive_Order", b =>
                {
                    b.Navigation("Supplier_Order_Product");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Room", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Room_Bookings");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Room_Type", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Shift", b =>
                {
                    b.Navigation("Employee_Shift");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Supplier", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Menlyn_Mews_API.Models.Domain.Supplier_Type", b =>
                {
                    b.Navigation("Suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
